# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zazazack.github.io
email: wilsonze@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    valuable learnings from development work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zazazack.github.io" # the base hostname & protocol for your site
twitter_username: za_za_zack
github_username:  zazazack

# Build settings
markdown: kramdown

# Plugins
gem:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-archives
