# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zazazack.github.io
email: wilsonze@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    learnings from development work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zazazack.github.io" # the base hostname & protocol for your site
twitter_username: za_za_zack
github_username:  zazazack

# Build settings
markdown: kramdown

# Plugins
gems:
    - jekyll-feed
    - jekyll-seo-tag    # see {% seo %} tag in _layouts/defautl.html
    - jekyll-archives

# Defaults
defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            analytics: true     # google analytics ref _includes/analytics.html & _layouts/defaults.html
    -
        scope:
            path: ""
            type: "posts"
        values:
            ads: true           # google adsense ref _includes/ads.html & _layouts/defaults.html
            analytics: true     # google analytics ref _includes/analytics.html & _layouts/defaults.html
            author: "Zack Wilson"
            comments: true      # disqus comments ref _layouts/post.html & _includes comments.html
